version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn app:app -b 0.0.0.0:5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    # DO NOT include a manual environment block if using .env

volumes:
  postgres_data:
